// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package location

import (
	"database/sql"
)

type Building struct {
	ID   int64
	Name string
}

type Friend struct {
	Member1ID int64
	Member2ID int64
}

type Member struct {
	ID     int64
	UserID int64
	Name   string
	Status string
	RoomID sql.NullInt64
}

type MembersBuilding struct {
	MemberID   int64
	BuildingID int64
}

type Room struct {
	ID         int64
	Name       string
	BuildingID int64
}

type Session struct {
	ID        int64
	RoomID    int64
	StartTime sql.NullTime
	EndTime   sql.NullTime
}

type User struct {
	ID       int64
	Username string
	Password string
	Salt     string
}
