// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: query.sql

package location

import (
	"context"
	"database/sql"
)

const getBuildingsByMemberId = `-- name: GetBuildingsByMemberId :many
SELECT b.id, b.name
FROM buildings b
JOIN members_buildings mb ON (b.id = mb.member_id)
WHERE mb.member_id = ?
LIMIT 10
`

func (q *Queries) GetBuildingsByMemberId(ctx context.Context, memberID int64) ([]Building, error) {
	rows, err := q.db.QueryContext(ctx, getBuildingsByMemberId, memberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Building
	for rows.Next() {
		var i Building
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMembersByRoomId = `-- name: GetMembersByRoomId :many
SELECT m.name, m.status, m.user_id
FROM members m
WHERE m.room_id = ?
LIMIT 10
`

type GetMembersByRoomIdRow struct {
	Name   string
	Status string
	UserID int64
}

func (q *Queries) GetMembersByRoomId(ctx context.Context, roomID sql.NullInt64) ([]GetMembersByRoomIdRow, error) {
	rows, err := q.db.QueryContext(ctx, getMembersByRoomId, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMembersByRoomIdRow
	for rows.Next() {
		var i GetMembersByRoomIdRow
		if err := rows.Scan(&i.Name, &i.Status, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRoomsByBuildingId = `-- name: GetRoomsByBuildingId :many
Select r.id, r.name
FROM  rooms r
WHERE r.building_id = ?
LIMIT 10
`

type GetRoomsByBuildingIdRow struct {
	ID   int64
	Name string
}

func (q *Queries) GetRoomsByBuildingId(ctx context.Context, buildingID int64) ([]GetRoomsByBuildingIdRow, error) {
	rows, err := q.db.QueryContext(ctx, getRoomsByBuildingId, buildingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRoomsByBuildingIdRow
	for rows.Next() {
		var i GetRoomsByBuildingIdRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRoomsByMemberId = `-- name: GetRoomsByMemberId :many
SELECT r.id, r.name
FROM rooms r
JOIN members_buildings mb ON (mb.building_id = r.building_id)
WHERE mb.member_id = ?
LIMIT 10
`

type GetRoomsByMemberIdRow struct {
	ID   int64
	Name string
}

func (q *Queries) GetRoomsByMemberId(ctx context.Context, memberID int64) ([]GetRoomsByMemberIdRow, error) {
	rows, err := q.db.QueryContext(ctx, getRoomsByMemberId, memberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRoomsByMemberIdRow
	for rows.Next() {
		var i GetRoomsByMemberIdRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
