// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package user

import ()

type Member struct {
	ID     int64
	UserID int64
	Name   string
	Status string
}

type User struct {
	ID       int64
	Username string
	Password string
	Salt     string
}
