name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Install sqlc
      run: go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest

  codegen: 
    needs: setup
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v3

    - name: Codegen sqlc
      run: make gen-sql

  test:
    needs: codegen
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v3

    - name: Short test
      run: make test
