name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  codegen: 
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Setup up sqlc
      uses: sqlc-dev/setup-sqlc@v4
      with:
        sqlc-version: '1.19.1'

    - name: Codegen sqlc
      run: make gen-sql

  test:
    needs: codegen
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v3

    - name: Short test
      run: make test
